version: "3.8"

services:
  dockerbot:
    build: .
    # image: techblog/dockerbot
    container_name: dockerbot
    restart: always
    environment:
      # - API_KEY=
      # - ALLOWED_IDS=
      - API_KEY_FILE=/run/secrets/dockerbot_api_key      
      - ALLOWED_IDS_FILE=/run/secrets/dockerbot_allowed_ids
    secrets:
      - dockerbot_api_key      
      - dockerbot_allowed_ids
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
 
secrets:
  dockerbot_allowed_ids:
    file: ${SECRETSDIR}/dockerbot_allowed_ids
  dockerbot_api_key:
    file: ${SECRETSDIR}/dockerbot_api_key

